#pragma once

#include "../../../lib/MCP23017/mcp23017.h"

extern MCP23017_HandleTypeDef hmcp01;
extern MCP23017_HandleTypeDef hmcp02;
extern MCP23017_HandleTypeDef hmcp03;

#define ROT_BTN_EXTI_IRQn EXTI15_10_IRQn

#define LED_0_PIN GPIO_PIN_8
#define LED_0_GPIO_PORT GPIOD
#define LED_1_PIN GPIO_PIN_9
#define LED_1_GPIO_PORT GPIOD
#define RX_SW_V1_PIN GPIO_PIN_10
#define RX_SW_V1_GPIO_PORT GPIOD
#define RX_SW_V2_PIN GPIO_PIN_11
#define RX_SW_V2_GPIO_PORT GPIOD
#define ROT_B_PIN GPIO_PIN_14
#define ROT_B_GPIO_PORT GPIOD
#define ROT_A_PIN GPIO_PIN_15
#define ROT_A_GPIO_PORT GPIOD
#define DISP_RST_PIN GPIO_PIN_0
#define DISP_RST_PORT GPIOD
#define DISP_DC_PIN GPIO_PIN_1
#define DISP_DC_PORT GPIOD
#define DISP_CE_PIN GPIO_PIN_15
#define DISP_CE_PORT GPIOA
#define DISP_LED_PIN GPIO_PIN_5
#define DISP_LED_PORT GPIOD
#define UNUSEDDEFINE 2

#ifdef PEPE
#define TESTTTTTT 2
#else

#define TESTTT 1

#endif

// Touch panel
#define TOUCH_CE_PIN GPIO_PIN_6
#define TOUCH_CE_PORT GPIOD
#define TOUCH_IRQ_PIN GPIO_PIN_7
#define TOUCH_IRQ_PORT GPIOD
#define TOUCH_DATA_IN_PORT GPIOE
#define TOUCH_DATA_IN_PIN GPIO_PIN_1 // Shared with POW_CTRL
#define TOUCH_DATA_OUT_PORT GPIOB
#define TOUCH_DATA_OUT_PIN GPIO_PIN_4
#define TOUCH_CLK_PORT GPIOB
#define TOUCH_CLK_PIN GPIO_PIN_6 // Shared with i2cBitBang

// Front panel back button
#define BACK_BTN_PIN GPIO_PIN_5
#define BACK_BTN_GPIO_PORT GPIOB
#define ROT_BTN_PIN GPIO_PIN_4
#define ROT_BTN_GPIO_PORT GPIOD
#define POW_CTRL_SET_PIN GPIO_PIN_9
#define POW_CTRL_SET_PORT GPIOB
#define POW_CTRL_CLK_PIN GPIO_PIN_8
#define POW_CTRL_CLK_PORT GPIOB
#define POW_CTRL_DATA_PIN GPIO_PIN_1
#define POW_CTRL_DATA_PORT GPIOE
// #define ANALOG_KEYBOARD_INTERRUPT_PIN GPIO_PIN_0
// #define ANALOG_KEYBOARD_INTERRUPT_PORT GPIOE
#define FRONT_PANEL_INTERRUPT_PIN_A GPIO_PIN_0
#define FRONT_PANEL_INTERRUPT_PIN_A_PORT GPIOE

/* These are the channels enabled in ADC3 */
#define S_STRENGTH_ADC_CHANNEL ADC_CHANNEL_12
#define AGC_ADC_CHANNEL ADC_CHANNEL_10
// #define ANALOG_KEYBOARD_ADC_CHANNEL ADC_CHANNEL_11
#define FOWARD_POWER_ADC_CHANNEL ADC_CHANNEL_3
#define REFLECTED_POWER_ADC_CHANNEL ADC_CHANNEL_1
#define INPUT_VOLTAGE_ADC_CHANNEL ADC_CHANNEL_2
#define POWER_AMP_TEMP_ADC_CHANNEL ADC_CHANNEL_0

void MX_GPIO_Init(void);
